"""Contains data for courses and stars.

Note that (1) the star count requirements do not necessarily factor in
the star count requirement of stars listed as prerequisites; (2) 100
coin stars are *not* included in this data. Utility function exist to
adjust/augment the data contained in this module to address both of
these limitations.
"""

from .constants import DataKeys, Locations


COURSES = [
    {
        DataKeys.COURSE_ID: "BOB",
        DataKeys.COURSE_NUMBER: 1,
        DataKeys.COURSE_NAME: "Bob-omb Battlefield",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "BOB1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Big Bob-omb on the Summit",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 0,
            },
            {
                DataKeys.STAR_ID: "BOB2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Footrace with Koopa the Quick",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 0,
            },
            {
                DataKeys.STAR_ID: "BOB3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Shoot to the Island in the Sky",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 0,
            },
            {
                DataKeys.STAR_ID: "BOB4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Find the 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 0,
            },
            {
                DataKeys.STAR_ID: "BOB5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Mario Wings to the Sky",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 10,
            },
            {
                DataKeys.STAR_ID: "BOB6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Behind Chain Chomp’s Gate",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 0,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "WF",
        DataKeys.COURSE_NUMBER: 2,
        DataKeys.COURSE_NAME: "Whomp’s Fortress",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "WF1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Chip off Whomp’s Block",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "WF2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "To the Top of the Fortress",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "WF3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Shoot into the Wild Blue",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "WF4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Red Coins on the Floating Isle",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "WF5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Fall onto the Caged Island",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "WF6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Blast Away the Wall",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "JRB",
        DataKeys.COURSE_NUMBER: 3,
        DataKeys.COURSE_NAME: "Jolly Roger Bay",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "JRB1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Plunder in the Sunken Ship",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "JRB2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Can the Eel Come out and Play?",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "JRB3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Treasure of the Ocean Cave",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "JRB4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Red Coins on the Ship Afloat",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "JRB5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Blast to the Stone Pillar",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "JRB6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Through the Jet Stream",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "CCM",
        DataKeys.COURSE_NUMBER: 4,
        DataKeys.COURSE_NAME: "Cool, Cool Mountain",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "CCM1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Slip Slidin’ Away",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CCM2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Li’l Penguin Lost",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CCM3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Big Penguin Race",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CCM4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Frosty Slide for 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CCM5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Snowman’s Lost his Head",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CCM6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Wall Kicks will Work",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "BBH",
        DataKeys.COURSE_NUMBER: 5,
        DataKeys.COURSE_NAME: "Big Boo’s Haunt",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "BBH1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Go on a Ghost Hunt",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
            {
                DataKeys.STAR_ID: "BBH2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Ride Big Boo’s Merry-Go-Round",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
            {
                DataKeys.STAR_ID: "BBH3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Secret of the Haunted Books",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
            {
                DataKeys.STAR_ID: "BBH4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Seek the 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
            {
                DataKeys.STAR_ID: "BBH5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Big Boo’s Balcony",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
            {
                DataKeys.STAR_ID: "BBH6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Eye to Eye in the Secret Room",
                DataKeys.STAR_LOCATION: Locations.COURTYARD,
                DataKeys.STAR_NUM_STARS_REQUIRED: 12,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "HMC",
        DataKeys.COURSE_NUMBER: 6,
        DataKeys.COURSE_NAME: "Hazy Maze Cave",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "HMC1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Swimming Beast in the Cavern",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "HMC2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Elevate for 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "HMC3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Metal-Head Mario Can Move!",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "HMC4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Navigating the Toxic Maze",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "HMC5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "A-Maze-ing Emergency Exit",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "HMC6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Watch for the Rolling Rocks",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "LLL",
        DataKeys.COURSE_NUMBER: 7,
        DataKeys.COURSE_NAME: "Lethal Lava Land",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "LLL1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Boil the Big Bully",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "LLL2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Bully the Bullies",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "LLL3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "8-Coin Puzzle with 15 Pieces",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "LLL4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Red-Hot Log Rolling",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "LLL5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Hot-Foot-It into the Volcano",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "LLL6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Elevator Tour in the Volcano",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "SSL",
        DataKeys.COURSE_NUMBER: 8,
        DataKeys.COURSE_NAME: "Shifting Sand Land",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "SSL1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "In the Talons of the Big Bird",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 10,
            },
            {
                DataKeys.STAR_ID: "SSL2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Shining Atop the Pyramid",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "SSL3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Inside the Ancient Pyramid",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "SSL4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Stand Tall on the Four Pillars",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "SSL5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Free Flying for 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 10,
            },
            {
                DataKeys.STAR_ID: "SSL6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Pyramid Puzzle",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "DDD",
        DataKeys.COURSE_NUMBER: 9,
        DataKeys.COURSE_NAME: "Dire, Dire Docks",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "DDD1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Board Bowser’s Sub",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "DDD2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Chests in the Current",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "DDD3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Pole-Jumping for Red Coins",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "DDD4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Through the Jet Stream",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "DDD5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "The Manta Ray’s Reward",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "DDD6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Collect the Caps",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "SL",
        DataKeys.COURSE_NUMBER: 10,
        DataKeys.COURSE_NAME: "Snowman’s Land",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "SL1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Snowman’s Big Head",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "SL2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Chill with the Bully",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "SL3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "In the Deep Freeze",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "SL4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Whirl from the Freezing Pond",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "SL5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Shell Shreddin’ for 8 Red Coins",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "SL6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Into the Igloo",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "WDW",
        DataKeys.COURSE_NUMBER: 11,
        DataKeys.COURSE_NAME: "Wet-Dry World",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "WDW1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Shocking Arrow Lifts!",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "WDW2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Top O’ The Town",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "WDW3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Secrets in the Shallows & Sky",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "WDW4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Express Elevators–Hurry Up!",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "WDW5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Go to Town for Red Coins",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "WDW6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Quick Race through Downtown",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "TTM",
        DataKeys.COURSE_NUMBER: 12,
        DataKeys.COURSE_NAME: "Tall, Tall Mountain",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "TTM1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Scale the Mountain",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "TTM2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "Mystery of the Monkey Cage",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "TTM3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Scary ‘Shrooms, Red Coins",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "TTM4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Mysterious Mountainside",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "TTM5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Breathtaking View from Bridge",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "TTM6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Blast to the Lonely Mushroom",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "THI",
        DataKeys.COURSE_NUMBER: 13,
        DataKeys.COURSE_NAME: "Tiny-Huge Island",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "THI1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Pluck the Piranha Flower",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "THI2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "The Tip Top of the Huge Island",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "THI3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Rematch with Koopa the Quick",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "THI4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Five Itty Bitty Secrets",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "THI5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Wiggler’s Red Coins",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "THI6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Make Wiggler Squirm",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "TTC",
        DataKeys.COURSE_NUMBER: 14,
        DataKeys.COURSE_NAME: "Tick Tock Clock",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "TTC1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Roll into the Cage",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "TTC2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "The Pit and the Pendulums",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "TTC3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Get a Hand",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "TTC4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Stomp on the Thwomp",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "TTC5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Timed Jumps on Moving Bars",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "TTC6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Stop Time for Red Coins",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "RR",
        DataKeys.COURSE_NUMBER: 15,
        DataKeys.COURSE_NAME: "Rainbow Ride",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "RR1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "Cruiser Crossing the Rainbow",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "RR2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "The Big House in the Sky",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "RR3",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "Coins Amassed in a Maze",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "RR4",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Swingin’ in the Breeze",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "RR5",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Tricky Triangles!",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "RR6",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Somewhere over the Rainbow",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
        ],
    },
    {
        DataKeys.COURSE_ID: "CASTLE",
        DataKeys.COURSE_NUMBER: 16,
        DataKeys.COURSE_NAME: "Peach’s Castle Secret Stars",
        DataKeys.COURSE_STARS: [
            {
                DataKeys.STAR_ID: "CASTLE_SS1",
                DataKeys.STAR_NUMBER: 1,
                DataKeys.STAR_NAME: "The Princess’s Secret Slide",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "CASTLE_SS2",
                DataKeys.STAR_NUMBER: 2,
                DataKeys.STAR_NAME: "The Princess’s Secret Slide (Return)",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 1,
            },
            {
                DataKeys.STAR_ID: "CASTLE_AQUA",
                DataKeys.STAR_NUMBER: 3,
                DataKeys.STAR_NAME: "The Secret Aquarium",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 3,
            },
            {
                DataKeys.STAR_ID: "CASTLE_TOAD1",
                DataKeys.STAR_NUMBER: 4,
                DataKeys.STAR_NAME: "Toad’s First Star",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "CASTLE_TOAD2",
                DataKeys.STAR_NUMBER: 5,
                DataKeys.STAR_NAME: "Toad’s Second Star",
                DataKeys.STAR_LOCATION: Locations.UPSTAIRS,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
            {
                DataKeys.STAR_ID: "CASTLE_TOAD3",
                DataKeys.STAR_NUMBER: 6,
                DataKeys.STAR_NAME: "Toad’s Third Star",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "CASTLE_MIPS1",
                DataKeys.STAR_NUMBER: 7,
                DataKeys.STAR_NAME: "MIPS Bunny Chase",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 15,
            },
            {
                DataKeys.STAR_ID: "CASTLE_MIPS2",
                DataKeys.STAR_NUMBER: 8,
                DataKeys.STAR_NAME: "MIPS Bunny Chase (Again)",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "CASTLE_WING_CAP",
                DataKeys.STAR_NUMBER: 9,
                DataKeys.STAR_NAME: "Tower of the Wing Cap",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 10,
            },
            {
                DataKeys.STAR_ID: "CASTLE_METAL_CAP",
                DataKeys.STAR_NUMBER: 10,
                DataKeys.STAR_NAME: "Cavern of the Metal Cap",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "CASTLE_VANISH_CAP",
                DataKeys.STAR_NUMBER: 11,
                DataKeys.STAR_NAME: "Vanish Cap Under the Moat",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "CASTLE_RAINBOW",
                DataKeys.STAR_NUMBER: 12,
                DataKeys.STAR_NAME: "Wing Mario Over the Rainbow",
                DataKeys.STAR_LOCATION: Locations.TIPPY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 50,
            },
            {
                DataKeys.STAR_ID: "CASTLE_BOWSER1",
                DataKeys.STAR_NUMBER: 13,
                DataKeys.STAR_NAME: "Bowser in the Dark World",
                DataKeys.STAR_LOCATION: Locations.LOBBY,
                DataKeys.STAR_NUM_STARS_REQUIRED: 8,
            },
            {
                DataKeys.STAR_ID: "CASTLE_BOWSER2",
                DataKeys.STAR_NUMBER: 14,
                DataKeys.STAR_NAME: "Bowser in the Fire Sea",
                DataKeys.STAR_LOCATION: Locations.BASEMENT,
                DataKeys.STAR_NUM_STARS_REQUIRED: 30,
            },
        ],
    },
]
